language: android
android:
  components:
    - tools
    - platform-tools
    - tools
before_install:
  - touch $HOME/.android/repositories.cfg
  - yes | sdkmanager "platforms;android-30"
  - yes | sdkmanager "build-tools;29.0.2"
script:
  - ./gradlew build check